// Sanctum Collective Properties — Live Listings
// Generated by CRM — Do not edit manually.
// To update: open crm.html, manage your listings, then click "Publish to Website".
window.SANCTUM_LISTINGS = [];
